services:
   postgres_db:
      image:
         postgres:latest
      environment:
         POSTGRES_USER: admin
         POSTGRES_PASSWORD: admin_password
         POSTGRES_DB: admin
      ports:
         - "5432:5432"
      volumes:
         - postgres_db-data:/var/lib/postgresql/data
         - ./WebApp:/docker-entrypoint-initdb.d
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U admin"]
         interval: 10s
         timeout: 5s
         retries: 5

   webapp: 
      build: 
         # context: .
         # dockerfile: ./WebApp/Dockerfile
         context: ./WebApp
         dockerfile: ./Dockerfile
      ports:
         - "8111:8111"
      depends_on:
         postgres_db:
            condition: service_healthy
      environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://*:8111
      - ConnectionStrings__DefaultConnection=Host=postgres_db;Port=5432;Database=admin;Username=admin;Password=admin_password
      command: >
         sh -c "dotnet ef database update && dotnet WebApp.dll"

volumes:
   postgres_db-data:
